/**
 * The §5 context bundle: one text file and one screenshot.
 *
 * §5 names this as a required fixture — "used to test that context is assembled
 * into the payload, survives a turn, and is not consumed by it". All three of
 * those are properties of a REAL pair of files rather than of strings built in a
 * test, which is why it is a directory and not a literal.
 *
 * The PNG is generated by `scripts/make-context-fixture.js` rather than pasted, so
 * it is reproducible and small; the Markdown is house-style notes, which is the
 * shape §8 C2 has in mind — a tone reference whose purpose cannot be inferred
 * from the file itself.
 *
 * The image is three horizontal bands, red then green then blue, and its content
 * is deliberately easy to state in words. That is what makes it usable as a live
 * check of §8 C3: a fixture whose content is hard to describe cannot test whether
 * the model described it.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const at = (name) => fileURLToPath(new URL(name, import.meta.url));

export const CONTEXT_BUNDLE = {
  text: {
    filename: 'tone-reference.md',
    type: 'text/markdown',
    path: at('tone-reference.md'),
    get bytes() {
      return readFileSync(this.path);
    },
    // §8 C2a: what she would have said in the prompt.
    description: 'house style — look to this for tone and sentence length, not content',
  },
  image: {
    filename: 'screenshot.png',
    type: 'image/png',
    path: at('screenshot.png'),
    get bytes() {
      return readFileSync(this.path);
    },
    description: 'a screenshot of the thread this came out of',
    /** What a model that actually read it should be able to say. */
    depicts: { bands: ['red', 'green', 'blue'], orientation: 'horizontal', size: '60x60' },
  },
};

export default CONTEXT_BUNDLE;
